// Body record support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using SupportLibrary.Database;


namespace SupportLibrary.Database
	{
	public partial class BodyRecord: IRecord
		{
		private int _ID = DatabaseSupport.InvalidID;
		private string _MessageIdentifier;			// Body.MessageIdentifier
		private string _HeaderText;			// Body.HeaderText
		private string _BodyText;			// Body.BodyText

		public BodyRecord()
			{
			}

		public BodyRecord(BodyRecord Other)
			{
			this.ID = Other.ID;
			this.MessageIdentifier = Other.MessageIdentifier;
			this.HeaderText = Other.HeaderText;
			this.BodyText = Other.BodyText;
			}

		public int ID
			{
			set
				{
				this._ID = value;
				}
			get
				{
				return _ID;
				}
			}

		public string MessageIdentifier
			{
			set
				{
				this._MessageIdentifier = value;
				}
			get
				{
				return (_MessageIdentifier == null ? "" : _MessageIdentifier);
				}
			}

		public string HeaderText
			{
			set
				{
				this._HeaderText = value;
				}
			get
				{
				return (_HeaderText == null ? "" : _HeaderText);
				}
			}

		public string BodyText
			{
			set
				{
				this._BodyText = value;
				}
			get
				{
				return (_BodyText == null ? "" : _BodyText);
				}
			}
		}
	}
