// Connection record support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using SupportLibrary.Database;


namespace SupportLibrary.Database
	{
	public partial class ConnectionRecord: IRecord
		{
		private int _ID = DatabaseSupport.InvalidID;
		private string _Remote;			// Connection.Remote
		private DateTime _StartTime;			// Connection.StartTime
		private DateTime? _EndTime;			// Connection.EndTime
		private bool _IsInbound;			// Connection.IsInbound

		public ConnectionRecord()
			{
			}

		public ConnectionRecord(ConnectionRecord Other)
			{
			this.ID = Other.ID;
			this.Remote = Other.Remote;
			this.StartTime = Other.StartTime;
			this.EndTime = Other.EndTime;
			this.IsInbound = Other.IsInbound;
			}

		public int ID
			{
			set
				{
				this._ID = value;
				}
			get
				{
				return _ID;
				}
			}

		public string Remote
			{
			set
				{
				this._Remote = value;
				}
			get
				{
				return (_Remote == null ? "" : _Remote);
				}
			}

		public DateTime StartTime
			{
			set
				{
				this._StartTime = value;
				}
			get
				{
				return _StartTime;
				}
			}

		public DateTime? EndTime
			{
			set
				{
				this._EndTime = value;
				}
			get
				{
				return _EndTime;
				}
			}

		public bool IsInbound
			{
			set
				{
				this._IsInbound = value;
				}
			get
				{
				return _IsInbound;
				}
			}
		}
	}
