// DeliveryAttempt record support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using SupportLibrary.Database;


namespace SupportLibrary.Database
	{
	public partial class DeliveryAttemptRecord: IRecord
		{
		private int _ID = DatabaseSupport.InvalidID;
		private int _HeaderID;			// DeliveryAttempt.HeaderID
		private DateTime _AttemptDateTime;			// DeliveryAttempt.AttemptDateTime
		private int? _ConnectionID;			// DeliveryAttempt.ConnectionID
		private string _MXAddress;			// DeliveryAttempt.MXAddress
		private bool _IsSuccess;			// DeliveryAttempt.IsSuccess
		private string _FailureReason;			// DeliveryAttempt.FailureReason

		public DeliveryAttemptRecord()
			{
			}

		public DeliveryAttemptRecord(DeliveryAttemptRecord Other)
			{
			this.ID = Other.ID;
			this.HeaderID = Other.HeaderID;
			this.AttemptDateTime = Other.AttemptDateTime;
			this.ConnectionID = Other.ConnectionID;
			this.MXAddress = Other.MXAddress;
			this.IsSuccess = Other.IsSuccess;
			this.FailureReason = Other.FailureReason;
			}

		public int ID
			{
			set
				{
				this._ID = value;
				}
			get
				{
				return _ID;
				}
			}

		public int HeaderID
			{
			set
				{
				this._HeaderID = value;
				}
			get
				{
				return _HeaderID;
				}
			}

		public DateTime AttemptDateTime
			{
			set
				{
				this._AttemptDateTime = value;
				}
			get
				{
				return _AttemptDateTime;
				}
			}

		public int? ConnectionID
			{
			set
				{
				this._ConnectionID = value;
				}
			get
				{
				return _ConnectionID;
				}
			}

		public string MXAddress
			{
			set
				{
				this._MXAddress = value;
				}
			get
				{
				return (_MXAddress == null ? "" : _MXAddress);
				}
			}

		public bool IsSuccess
			{
			set
				{
				this._IsSuccess = value;
				}
			get
				{
				return _IsSuccess;
				}
			}

		public string FailureReason
			{
			set
				{
				this._FailureReason = value;
				}
			get
				{
				return (_FailureReason == null ? "" : _FailureReason);
				}
			}
		}
	}
