// Header record support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using SupportLibrary.Database;


namespace SupportLibrary.Database
	{
	public partial class HeaderRecord: IRecord
		{
		private int _ID = DatabaseSupport.InvalidID;
		private int? _BodyID;			// Header.BodyID
		private string _Sender;			// Header.Sender
		private string _Recipient;			// Header.Recipient
		private int _RecvConnectionID;			// Header.RecvConnectionID
		private int? _SendConnectionID;			// Header.SendConnectionID
		private DateTime _ReceivedDateTime;			// Header.ReceivedDateTime
		private DateTime? _DeliveredDateTime;			// Header.DeliveredDateTime
		private DateTime? _ExpiredDateTime;			// Header.ExpiredDateTime

		public HeaderRecord()
			{
			}

		public HeaderRecord(HeaderRecord Other)
			{
			this.ID = Other.ID;
			this.BodyID = Other.BodyID;
			this.Sender = Other.Sender;
			this.Recipient = Other.Recipient;
			this.RecvConnectionID = Other.RecvConnectionID;
			this.SendConnectionID = Other.SendConnectionID;
			this.ReceivedDateTime = Other.ReceivedDateTime;
			this.DeliveredDateTime = Other.DeliveredDateTime;
			this.ExpiredDateTime = Other.ExpiredDateTime;
			}

		public int ID
			{
			set
				{
				this._ID = value;
				}
			get
				{
				return _ID;
				}
			}

		public int? BodyID
			{
			set
				{
				this._BodyID = value;
				}
			get
				{
				return _BodyID;
				}
			}

		public string Sender
			{
			set
				{
				this._Sender = value;
				}
			get
				{
				return (_Sender == null ? "" : _Sender);
				}
			}

		public string Recipient
			{
			set
				{
				this._Recipient = value;
				}
			get
				{
				return (_Recipient == null ? "" : _Recipient);
				}
			}

		public int RecvConnectionID
			{
			set
				{
				this._RecvConnectionID = value;
				}
			get
				{
				return _RecvConnectionID;
				}
			}

		public int? SendConnectionID
			{
			set
				{
				this._SendConnectionID = value;
				}
			get
				{
				return _SendConnectionID;
				}
			}

		public DateTime ReceivedDateTime
			{
			set
				{
				this._ReceivedDateTime = value;
				}
			get
				{
				return _ReceivedDateTime;
				}
			}

		public DateTime? DeliveredDateTime
			{
			set
				{
				this._DeliveredDateTime = value;
				}
			get
				{
				return _DeliveredDateTime;
				}
			}

		public DateTime? ExpiredDateTime
			{
			set
				{
				this._ExpiredDateTime = value;
				}
			get
				{
				return _ExpiredDateTime;
				}
			}
		}
	}
