// AllowedDataSource Web Interface support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Web.UI.WebControls;
using SupportLibrary.Database;

namespace SupportLibrary.DataSource
	{
	public partial class AllowedDataSource : ObjectDataSource
		{
		public static IList<AllowedRecord> ReadAllRecords()
			{
			DALContainer dc = DALContainer.GetDALContainer();
			AllowedDAL dal = dc.GetAllowedDAL();
			return dal.ReadAllRecords();
			}

		public static AllowedRecord ReadRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			AllowedDAL dal = dc.GetAllowedDAL();
			return dal.ReadRecord(RecordID);
			}

		public static void CreateRecord(AllowedRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			AllowedDAL dal = dc.GetAllowedDAL();
			dal.CreateRecord(Record);
			}

		public static void UpdateRecord(AllowedRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			AllowedDAL dal = dc.GetAllowedDAL();
			dal.UpdateRecord(Record);
			}

		public static void DeleteRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			AllowedDAL dal = dc.GetAllowedDAL();
			dal.DeleteRecord(RecordID);
			}
		}
	}
