// BodyDataSource Web Interface support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Web.UI.WebControls;
using SupportLibrary.Database;

namespace SupportLibrary.DataSource
	{
	public partial class BodyDataSource : ObjectDataSource
		{
		public static IList<BodyRecord> ReadAllRecords()
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			return dal.ReadAllRecords();
			}

		public static BodyRecord ReadRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			return dal.ReadRecord(RecordID);
			}

		public static BodyRecord ReadRecordByMessageIdentifier(string MessageIdentifier)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			return dal.ReadRecordByMessageIdentifier(MessageIdentifier);
			}

		public static void CreateRecord(BodyRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			dal.CreateRecord(Record);
			}

		public static void UpdateRecord(BodyRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			dal.UpdateRecord(Record);
			}

		public static void DeleteRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			BodyDAL dal = dc.GetBodyDAL();
			dal.DeleteRecord(RecordID);
			}
		}
	}
