// DeliveryAttemptDataSource Web Interface support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Web.UI.WebControls;
using SupportLibrary.Database;

namespace SupportLibrary.DataSource
	{
	public partial class DeliveryAttemptDataSource : ObjectDataSource
		{
		public static IList<DeliveryAttemptRecord> ReadAllRecords()
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			return dal.ReadAllRecords();
			}

		public static DeliveryAttemptRecord ReadRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			return dal.ReadRecord(RecordID);
			}

		public static IList<DeliveryAttemptRecord> ReadAllRecordsByHeaderID(int HeaderID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			return dal.ReadAllRecordsByHeaderID(HeaderID);
			}

		public static IList<DeliveryAttemptRecord> ReadAllRecordsByConnectionID(int ConnectionID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			return dal.ReadAllRecordsByConnectionID(ConnectionID);
			}

		public static void CreateRecord(DeliveryAttemptRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			dal.CreateRecord(Record);
			}

		public static void UpdateRecord(DeliveryAttemptRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			dal.UpdateRecord(Record);
			}

		public static void DeleteRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			DeliveryAttemptDAL dal = dc.GetDeliveryAttemptDAL();
			dal.DeleteRecord(RecordID);
			}
		}
	}
