// HeaderDataSource Web Interface support file
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Web.UI.WebControls;
using SupportLibrary.Database;

namespace SupportLibrary.DataSource
	{
	public partial class HeaderDataSource : ObjectDataSource
		{
		public static IList<HeaderRecord> ReadAllRecords()
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			return dal.ReadAllRecords();
			}

		public static HeaderRecord ReadRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			return dal.ReadRecord(RecordID);
			}

		public static IList<HeaderRecord> ReadAllRecordsByBodyID(int BodyID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			return dal.ReadAllRecordsByBodyID(BodyID);
			}

		public static IList<HeaderRecord> ReadAllRecordsByRecvConnectionID(int RecvConnectionID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			return dal.ReadAllRecordsByRecvConnectionID(RecvConnectionID);
			}

		public static IList<HeaderRecord> ReadAllRecordsBySendConnectionID(int SendConnectionID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			return dal.ReadAllRecordsBySendConnectionID(SendConnectionID);
			}

		public static void CreateRecord(HeaderRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			dal.CreateRecord(Record);
			}

		public static void UpdateRecord(HeaderRecord Record)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			dal.UpdateRecord(Record);
			}

		public static void DeleteRecord(int RecordID)
			{
			DALContainer dc = DALContainer.GetDALContainer();
			HeaderDAL dal = dc.GetHeaderDAL();
			dal.DeleteRecord(RecordID);
			}
		}
	}
