// Allowed Data Access Layer
//
// DO NOT MODIFY THIS FILE DIRECTLY.  IT WILL BE OVERWRITTEN.
// Generated by SQLServerGenerator.cs
// Copyright (c) 2010, Chris Laforet Software.  All rights reserved
//
// Generated at 04/24/2010 03:03


using System;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Data.Sql;
using System.Collections.Generic;
using SupportLibrary.Database;


namespace SupportLibrary.Database
	{
	public partial class AllowedDAL: IDAL<AllowedRecord>
		{
		private readonly string _connectionString;
		public readonly string TableName = "Allowed";

		public AllowedDAL(string ConnectionString)
			{
			_connectionString = ConnectionString;
			}

		static public AllowedRecord ReapRecord(SqlDataReader Reader)
			{
			int ID = Reader.GetInt32(Reader.GetOrdinal("ID"));
			string IP = Reader.GetString(Reader.GetOrdinal("IP"));
			string Subnet = Reader.GetString(Reader.GetOrdinal("Subnet"));
			AllowedRecord record = new AllowedRecord();

			record.ID = ID;
			record.IP = IP;
			record.Subnet = Subnet;
			return record;
			}

		public virtual IList<AllowedRecord> ReadAllRecords()
			{
			IList<AllowedRecord> list = new List<AllowedRecord>(64);
			SqlConnection conn = new SqlConnection(_connectionString);
			conn.Open();
			if (conn != null)
				{
				try
					{
					SqlCommand command = new SqlCommand("SELECT * FROM [Allowed]",conn);
					SqlDataReader rs = command.ExecuteReader();
					while (rs.Read())
						list.Add(ReapRecord(rs));
					rs.Close();
					}
				finally
					{
					if (conn != null)
						conn.Close();
					}
				}
			return list;
			}

		public virtual AllowedRecord ReadRecord(int RecordID)
			{
			AllowedRecord record = null;
			SqlConnection conn = new SqlConnection(_connectionString);
			conn.Open();
			if (conn != null)
				{
				try
					{
					SqlCommand command = new SqlCommand("SELECT * FROM [Allowed] WHERE ID=@ID",conn);
					SqlParameter param = new SqlParameter("@ID",SqlDbType.Int,0);
					param.Value = RecordID;
					command.Parameters.Add(param);
					SqlDataReader rs = command.ExecuteReader();
					if (rs.Read())
						record = ReapRecord(rs);
					rs.Close();
					}
				finally
					{
					if (conn != null)
						conn.Close();
					}
				}
			return record;
			}

		public virtual void CreateRecord(AllowedRecord record)
			{
			SqlConnection conn = new SqlConnection(_connectionString);
			conn.Open();
			if (conn != null)
				{
				try
					{
					string sql = "INSERT INTO [Allowed] " + 
					"(IP,Subnet	) " +
					"VALUES (@IP,@Subnet	)";
					SqlCommand command = new SqlCommand(sql,conn);
					SqlParameter param = new SqlParameter("@IP",SqlDbType.VarChar,0);
					param.Value = record.IP;
					command.Parameters.Add(param);
					param = new SqlParameter("@Subnet",SqlDbType.VarChar,0);
					param.Value = record.Subnet;
					command.Parameters.Add(param);
					command.ExecuteNonQuery();
					record.ID = DatabaseSupport.GetIdentity(conn);
					}
				finally
					{
					if (conn != null)
						conn.Close();
					}
				}
			}

		public virtual int CreateRecord(string IP,string Subnet)
			{
			// populate the record with items
			AllowedRecord record = new AllowedRecord();
			record.IP = IP;
			record.Subnet = Subnet;

			// write the record out
			CreateRecord(record);
			return record.ID;
			}

		public virtual void UpdateRecord(AllowedRecord record)
			{
			SqlConnection conn = new SqlConnection(_connectionString);
			conn.Open();
			if (conn != null)
				{
				try
					{
					string sql = "UPDATE [Allowed] " +
					"SET IP=@IP,Subnet=@Subnet WHERE ID=@ID";
					SqlCommand command = new SqlCommand(sql,conn);
					SqlParameter param = new SqlParameter("@IP",SqlDbType.VarChar,0);
					param.Value = record.IP;
					command.Parameters.Add(param);
					param = new SqlParameter("@Subnet",SqlDbType.VarChar,0);
					param.Value = record.Subnet;
					command.Parameters.Add(param);
					param = new SqlParameter("@ID",SqlDbType.Int,0);
					param.Value = record.ID;
					command.Parameters.Add(param);
					command.ExecuteNonQuery();
					}
				finally
					{
					if (conn != null)
						conn.Close();
					}
				}
			}

		public virtual void UpdateRecord(int ID,string IP,string Subnet)
			{
			// populate the record with items
			AllowedRecord record = new AllowedRecord();
			record.ID = ID;
			record.IP = IP;
			record.Subnet = Subnet;

			// write the record out
			UpdateRecord(record);
			}

		public virtual void DeleteRecord(int RecordID)
			{
			SqlConnection conn = new SqlConnection(_connectionString);
			conn.Open();
			if (conn != null)
				{
				try
					{
					string sql = "DELETE FROM [Allowed] WHERE ID=@ID";
					SqlCommand command = new SqlCommand(sql,conn);
					SqlParameter param = new SqlParameter("@ID",SqlDbType.Int,0);
					param.Value = RecordID;
					command.Parameters.Add(param);
					command.ExecuteNonQuery();
					}
				finally
					{
					if (conn != null)
						conn.Close();
					}
				}
			}

		public virtual void DeleteRecord(AllowedRecord record)
			{
			DeleteRecord(record.ID);
			}
		}
	}
